apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-assistant
  labels:
    app: product-assistant
spec:
  replicas: 1   # ðŸ”‘ MUST be 1 on free-tier EKS
  selector:
    matchLabels:
      app: product-assistant

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0           # ðŸ”‘ prevent extra pods
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: product-assistant
    spec:
      containers:
      - name: product-assistant
        image: 476768693517.dkr.ecr.us-east-1.amazonaws.com/product-assistant:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 8000

        resources:            # ðŸ”‘ REQUIRED on t3.micro
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"

        env:
        - name: GROQ_API_KEY
          valueFrom:
            secretKeyRef:
              name: product-assistant-secrets
              key: GROQ_API_KEY

        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: product-assistant-secrets
              key: HF_TOKEN

        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: product-assistant-secrets
              key: OPENAI_API_KEY

        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: product-assistant-secrets
              key: GOOGLE_API_KEY

        - name: ASTRA_DB_API_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: product-assistant-secrets
              key: ASTRA_DB_API_ENDPOINT

        - name: ASTRA_DB_APPLICATION_TOKEN
          valueFrom:
            secretKeyRef:
              name: product-assistant-secrets
              key: ASTRA_DB_APPLICATION_TOKEN

        - name: ASTRA_DB_KEYSPACE
          valueFrom:
            secretKeyRef:
              name: product-assistant-secrets
              key: ASTRA_DB_KEYSPACE
